### ISSUE TITLE
Noetic Python 2 dependency on qt5 webkit bindings

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/webkit_dependency#2]
It looks like the [noetic source entry for `webkit_dependency`](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/noetic/distribution.yaml#L313-L318) depends on the Python 2 rosdep key `python-qt5-bindings-webkit`.

https://github.com/ros-visualization/webkit_dependency/blob/372a30e6adb82a6b1d02a1a5bf8ab5a1be3f734a/package.xml#L11

Maybe it should use the [rosdep key `python3-qt5-bindings-webkit`](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/rosdep/python.yaml#L5307-L5311) instead?

**Comment by dirk-thomas** [comment]
> Maybe it should use the rosdep key `python3-qt5-bindings-webkit` instead?

Indeed, please consider to contribute a pull request adding the dependency with a Python version condition.
